// Generated by Selenium IDE
const { Builder, By, Key, until, Capabilities } = require('selenium-webdriver')
const assert = require('assert')

describe('search-devops', function() {
  this.timeout(30000)
  let driver
  let vars
  let capabilities = new Capabilities().setBrowserName("operablink")
  beforeEach(async function() {
    driver = await new Builder().usingServer("http://localhost:4444").withCapabilities(capabilities).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search-devops', async function() {
    await driver.get("https://www.google.com/")
    await driver.switchTo().frame(0)
    await driver.wait(until.elementLocated(By.css("#introAgreeButton .RveJvd"))).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.name("q")).click()
    await driver.findElement(By.name("q")).sendKeys("devops")
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    await driver.wait(until.elementLocated(By.xpath("//div[@id=\'rso\']/div[3]/div/div/div/a/h3/span"))).click()
  })
})
